import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const source = readFileSync(new URL("../contracts/KentirToken.sol", import.meta.url), "utf8");
const input = {
  language: "Solidity",
  sources: { "KentirToken.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};
const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  console.error(errors);
  process.exit(1);
}
const contract = output.contracts["KentirToken.sol"]["KentirToken"];
const out = `// GENERATED by scripts/compile-token.mjs — do not hand-edit.
export const TOKEN_SOLC_VERSION = "0.8.26";
export const TOKEN_ABI = ${JSON.stringify(contract.abi)} as const;
export const TOKEN_BYTECODE = "0x${contract.evm.bytecode.object}";
`;
writeFileSync(new URL("../lib/token-artifact.ts", import.meta.url), out);
console.log("wrote lib/token-artifact.ts");
