import { readFileSync, writeFileSync } from "node:fs";
import solc from "solc";

const root = (p) => readFileSync(new URL(p, import.meta.url), "utf8");
const input = {
  language: "Solidity",
  sources: {
    "KentirToken.sol": { content: root("../contracts/KentirToken.sol") },
    "KentirLauncher.sol": { content: root("../contracts/KentirLauncher.sol") },
  },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};
const output = JSON.parse(solc.compile(JSON.stringify(input)));
const errors = (output.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  console.error(errors);
  process.exit(1);
}
const token = output.contracts["KentirToken.sol"]["KentirToken"];
const launcher = output.contracts["KentirLauncher.sol"]["KentirLauncher"];

const tokenOut = `// GENERATED by scripts/compile-token.mjs — do not hand-edit.
export const TOKEN_SOLC_VERSION = "0.8.26";
export const TOKEN_ABI = ${JSON.stringify(token.abi)} as const;
export const TOKEN_BYTECODE = "0x${token.evm.bytecode.object}";
`;
const launcherOut = `// GENERATED by scripts/compile-token.mjs — do not hand-edit.
export const LAUNCHER_ABI = ${JSON.stringify(launcher.abi)} as const;
export const LAUNCHER_BYTECODE = "0x${launcher.evm.bytecode.object}";
`;
writeFileSync(new URL("../lib/token-artifact.ts", import.meta.url), tokenOut);
writeFileSync(new URL("../lib/launcher-artifact.ts", import.meta.url), launcherOut);
console.log("wrote lib/token-artifact.ts + lib/launcher-artifact.ts");
